version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: new_password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://myuser:new_password@db:5432/mydatabase"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  postgres_data:
